[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]] 
  from = "https://master--zippy-cheesecake-3b43e1.netlify.app/*"
  to = "https://factwise.io/blog/:splat" 
  status = 200 
  force = true 